### PR TITLE
Only force request on short queue if user is the sole requester

### PR DESCRIPTION
**Pull request by penamety**
Allow multiple requests when the queue is shorter than
MIN_QUEUE_SONGS_LIMIT as before, but only when the user is currently the
only one requesting (also taking into account the requester of current
song playing).

### CODE REVIEW

**Comment by penamety** [comment]
Implements the allowing of multiple requests as per what is mentioned [here](https://www.scenemusic.net/forum/thread/1472/) :

>only when queue completely empty and nobody else requests inbetween

During short queues and for example two users requesting in total this change allows a user to request a song during the duration of their current request playing, without the other user being able to hog the queue up to MIN_QUEUE_SONGS_LIMIT, but instead have a maximum of SONGS_IN_QUEUE pending requests. Ordinary limits are removed (and thus forcing enabled) only if nobody else is requesting with a short queue.

Things that could be taken into account but currently aren't in order to not further complicate the code at this point:

* djrandom counts as a requester. User also has to wait for djrandom's currently playing song to finish before being able to queue up to MIN_QUEUE_SONGS_LIMIT. A minor inconvenience I think.

* In case of SONGS_IN_QUEUE being 1: When there are only two requesters they could perhaps be allowed to alternate requesting up to MIN_QUEUE_SONGS_LIMIT, right now that's not the case.

**Comment by arabek** [comment]
I'm not sure i wan't to change the current behavior.

**Comment by penamety** [comment]
I thought what was said in the thread sounded great and simple but (IMHO) unfortunately it's not how it currently works. Any idea what your hesitation is?
On Nectarine there are users who try to hog the queue up to MIN_QUEUE_SONGS_LIMIT requests when they can and are unable to be polite enough to give others the opportunity to request, resulting in a 3:1 request ratio when there are 2 requesters (and 2:1:1 with 3 requesters). With this change when there really is only one requester the behaviour is still the same as before: queue can be filled by that person up to the limit. In all other cases it's an equal affair.

**Comment by arabek** [comment]
👍

**Pull request merged**
